name: Setup Os

description: Provisions OS deps

runs:
  using: "composite"

  steps:

    - name: Update System 
      shell: bash
      run: |
        sudo apt update -y -qq
    #
    # was getting this error when trying to build with libpugixml-dev
    # [release-please/release-please]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/5] user= workdir=
    #     | -- The C compiler identification is GNU 9.4.0
    #     | -- The CXX compiler identification is GNU 9.4.0
    #     | -- Detecting C compiler ABI info
    #     | -- Detecting C compiler ABI info - done
    #     | -- Check for working C compiler: /usr/bin/cc - skipped
    #     | -- Detecting C compile features
    #     | -- Detecting C compile features - done
    #     | -- Detecting CXX compiler ABI info
    #     | -- Detecting CXX compiler ABI info - done
    #     | -- Check for working CXX compiler: /usr/bin/c++ - skipped
    #     | -- Detecting CXX compile features
    #     | -- Detecting CXX compile features - done
    #     | -- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
    #     | -- Checking for one of the modules 'glfw3'
    #     | -- Found Vulkan: /usr/lib/x86_64-linux-gnu/libvulkan.so (found version "131")  missing components: glslc glslangValidator
    #     | -- Found CURL: /usr/lib/x86_64-linux-gnu/libcurl.so (found version "7.68.0")  
    #     | -- Configuring done (0.9s)
    #     | CMake Error at CMakeLists.txt:72 (target_link_libraries):
    #     |   Target "Lamp" links to:
    #     | 
    #     |     pugixml::pugixml
    #     | 
    #     |   but the target was not found.  Possible reasons include:
    #     | 
    #     |     * There is a typo in the target name.
    #     |     * A find_package call is missing for an IMPORTED target.
    #     |     * An ALIAS target is missing.
    #     | 
    #     | 
    #     | 
    #     | -- Generating done (0.0s)
    #     | CMake Generate step failed.  Build files cannot be regenerated correctly.
    #
    # so on advice from : https://stackoverflow.com/a/68752679
    # we install with vcpkg instead 
    - name: Install Dev Dependencies
      shell: bash
      run: |
        sudo apt install  -y -qq \
          libvulkan-dev \
          libglfw3-dev \
          libcurl4-openssl-dev \
          libpugixml-dev \
          pkg-config \
          g++ \
          gcc

    - name: Install Runtime Dependencies
      shell: bash
      run: |
        sudo apt install  -y -qq \
          zenity
