name: Build

description: Creates a build


inputs:
  BuildType:
    description: "DEBUG or RELEASE"
    required: true
    default: DEBUG
  OutputName:
    description: "Name of the output build"
    required: false
    default: lamp-x11


runs:
  using: "composite"

  steps:

      - name: Build Artifact
        shell: bash
        env:
          BUILD_TYPE: ${{inputs.BuildType}}
        run: |
          cmake \
            -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
            -DCMAKE_MAKE_PROGRAM=ninja \
            -B ${{github.workspace}}/build \
            -G Ninja \
            -S ./

          # do ninja things
          cd ./build
          ninja

          echo "📦 Build complete"

          # echo "output_name=${{inputs.OutputName}}" >> $GITHUB_OUTPUT
