on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

name: Release Management

jobs:
  release-please:
    
    runs-on: ubuntu-22.04

    steps:

      - uses: google-github-actions/release-please-action@v3
        id: release-please
        # skip during local actions testing
        if: ${{ !env.ACT }}
        with:
          release-type: simple
          extra-files: |
            VERSION
      #
      # This step serves as an interop layer between the online and offline
      # when online, we use release-please and further execution is gated by the release_created output
      # when offline, we skip release-please and set release_created to true to test creating a release build
      - name: Declare Release Created
        id: release
        env:
            RELEASE_PLEASE_TAG: ${{ steps.release-please.outputs.release_tag }}
            RELEASE_PLEASE_RELEASE_CREATED: ${{ steps.release-please.outputs.releases_created }}
        run: |
          if [ "${{ env.ACT }}" = "true" ]; then

            echo "OFFLINE: release created"
            RELEASE_CREATED="true"
            TAG_CREATED=$(git describe --tags --abbrev=1)
          
          elif [ "${RELEASE_PLEASE_RELEASE_CREATED}" = "true" ]; then
            
            echo "ONLINE: release created"
            RELEASE_CREATED="true"
            TAG_CREATED=${RELEASE_PLEASE_TAG}
          
          else 
          
            echo "ONLINE: release not created"
            RELEASE_CREATED="false"

          fi

          echo "release_created=${RELEASE_CREATED}" >> $GITHUB_OUTPUT
          echo "release_tag=${TAG_CREATED}" >> $GITHUB_OUTPUT

      - name: Checkout
        if: ${{ steps.release.outputs.release_created == 'true' }}
        uses: actions/checkout@v3

      - name: OS Deps
        if: ${{ steps.release.outputs.release_created == 'true' }}
        uses: ./.github/actions/setup-os
      
      # Just let ASDF do its thing. It's far easier and more reliable than trying to do it ourselves.
      - name: Tooling
        if: ${{ steps.release.outputs.release_created == 'true' }}
        uses: ./.github/actions/setup-tooling
        with:
          SetupCommand: ./setup.sh
      
      - name: Build
        if: ${{ steps.release.outputs.release_created == 'true' }}
        run: |
          ./build.sh Debug

      # only upload the release artifact if we're online and not testing
      - name: Upload Release Artifact
        if: ${{ steps.release.outputs.release_created == 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ "${{ env.ACT }}" = "true" ]; then
            echo "OFFLINE: skipping upload"
            cp -r ./build/Lamp ./build/lamp-x11-${{ steps.release.outputs.release_tag }}
          else
            gh release upload ${{ steps.release.outputs.release_tag }} ./build/Lamp#lamp-x11-${{ steps.release.outputs.release_tag }}
          fi
          